[package]
name = "Weiawaga"
authors = ["Heiaha"]
repository = "https://github.com/Heiaha/Weiawaga"
version = "6.0.0"
edition = "2024"
readme = "README.md"
rust-version = "1.89.0"

[dependencies]
arrayvec = "0.7.6"
bytemuck = { version = "1", features = ["min_const_generics"] }
regex = "1.11.1"
rand = "0.9.1"
wide = "1.5.0"
parquet = { version = "59.1.0", default-features = false, features = ["arrow", "zstd"], optional = true }
arrow-array = { version = "59.1.0", optional = true }
arrow-schema = { version = "59.1.0", optional = true }
pyrrhic-rs = { version = "0.2.0", optional = true }

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 1
lto = true
panic = "abort"

[features]
datagen = ["dep:parquet", "dep:arrow-array", "dep:arrow-schema", "dep:pyrrhic-rs"]
